[package]
name = 'nftmachine'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'aptos-framework-v1.9.0'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosToken]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'aptos-framework-v1.9.0'
subdir = 'aptos-move/framework/aptos-token'

[addresses]
nftmachine_addr = "7803a09b4c9e2d140edeaa0b4ea2711276ff6b901d88f499a0173d6c62b3b767"