[package]
name = 'nftmachine'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosToken]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-token'

[addresses]
admin_addr = "637b3459fa497e5a52692ec3acb1b9b1863cc284b2d8a52a10d4ffd681d7dfb1"
source_addr = "637b3459fa497e5a52692ec3acb1b9b1863cc284b2d8a52a10d4ffd681d7dfb1"
nftmachine = "3236b9a15dd42216bc4b8c4b7de458ff8fe2ab824ecfe4029fe7fad74ba87533"
nftmachine_addr = "3236b9a15dd42216bc4b8c4b7de458ff8fe2ab824ecfe4029fe7fad74ba87533"